name: takasukonomuro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/yaki.jpg
    - assets/images/fundo_login.png



  fonts:
     - family: PlayFairDisplay
       fonts:
         - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
         - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
           weight: 700
         - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-SemiBold.ttf
           weight: 500
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto/Roboto-Bold.ttf
           weight: 700
     